### ISSUE TITLE
Cannot import via `commonMain.dependencies`

### ISSUE THREAD

**Issue by Xerosigma** [ChainTechNetwork/sdp-ssp-compose-multiplatform#2]
Putting this in `commonMain.dependencies ` did not work for me.

```
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve network.chaintech:sdp-ssp-compose-multiplatform:1.0.1.
Required by:
    project :composeApp
Caused by: org.gradle.internal.component.NoMatchingConfigurationSelectionException: No matching variant of network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'org.jetbrains.kotlin.wasm.target' with value 'js' but:
  - Variant 'iosArm64ApiElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library for use during 'kotlin-api':
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosArm64MetadataElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library:
      - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosArm64SourcesElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1:
      - Incompatible because this component declares documentation for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosSimulatorArm64ApiElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library for use during 'kotlin-api':
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosSimulatorArm64MetadataElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library:
      - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosSimulatorArm64SourcesElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1:
      - Incompatible because this component declares documentation for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosX64ApiElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library for use during 'kotlin-api':
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosX64MetadataElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library:
      - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'iosX64SourcesElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1:
      - Incompatible because this component declares documentation for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'metadataApiElements' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library:
      - Incompatible because this component declares a component for use during 'kotlin-metadata', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a component for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'metadataSourcesElements' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1:
      - Incompatible because this component declares documentation for use during 'kotlin-runtime', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed a library for use during 'kotlin-api', as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'releaseApiElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library for use during compile-time:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'releaseRuntimeElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a library for use during runtime:
      - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
  - Variant 'releaseSourcesElements-published' capability network.chaintech:sdp-ssp-compose-multiplatform:1.0.1 declares a component for use during runtime:
      - Incompatible because this component declares documentation, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
      - Other compatible attributes:
          - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
          - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')
	at org.gradle.internal.component.SelectionFailureHandler.noMatchingConfigurationSelectionFailure(SelectionFailureHandler.java:282)
	at org.gradle.internal.component.model.AttributeMatchingConfigurationSelector.selectVariantsUsingAttributeMatching(AttributeMatchingConfigurationSelector.java:132)
	at org.gradle.internal.component.model.AttributeMatchingConfigurationSelector.selectVariantsUsingAttributeMatching(AttributeMatchingConfigurationSelector.java:68)
	at org.gradle.internal.component.model.LocalComponentDependencyMetadata.selectVariants(LocalComponentDependencyMetadata.java:125)
	at org.gradle.internal.component.model.DelegatingDependencyMetadata.selectVariants(DelegatingDependencyMetadata.java:46)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.calculateTargetConfigurations(EdgeState.java:262)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.attachToTargetConfigurations(EdgeState.java:147)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:345)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:237)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:174)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:147)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:210)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:86)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:73)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:717)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$1.call(DefaultConfiguration.java:709)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:709)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$resolveExclusively$3(DefaultConfiguration.java:689)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$CalculatedModelValueImpl.update(DefaultProjectStateRegistry.java:504)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveExclusively(DefaultConfiguration.java:686)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:682)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:658)
	at org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
```

**Comment by ctn-mobile-innovation** [comment]
It has been fixed in latest version!
